# Selections

Often when we're working with numpy we're only interested in a portion of the data in our arrays. The `[]` on `ndarray` allows us select portions of the data in the array in a variety of interesting ways.

The exercises in this notebook will teach you how to select elements out of arrays in a variety of ways.

In [1]:
import numpy as np

rand = np.random.RandomState(42)  # Use a deterministic seed.

## Exercise: 1-dimensional selection

Write expressions to select the following elements from the array:

1. first element
1. second element
1. last element
1. second to last element
1. first 5 elements
1. last 5 elements
1. elements at indices 1, 4, 7, and 13
1. elements with even indices
1. the entire array, in reverse order
1. every other element, starting at index 3 (inclusive) ending at index 17 (exclusive)

In [2]:
array = np.arange(20)

In [3]:
array[0]

0

In [4]:
array[1]

1

In [5]:
array[-1]

19

In [6]:
array[-2]

18

In [7]:
array[:5]

array([0, 1, 2, 3, 4])

In [8]:
array[-5:]

array([15, 16, 17, 18, 19])

In [11]:
print(array[1],
array[4],
array[7],
array[13])

1 4 7 13


In [15]:
array[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
array[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [17]:
array[3:17:2]

array([ 3,  5,  7,  9, 11, 13, 15])

## Exercise: 2-dimensional selection

Write expressions to select the following elements from the array.

1. scalar value at coordinates `[3, 6]`
1. top-left scalar value
1. first row
1. first column
1. second column
1. last column
1. first 5 columns
1. last 5 columns
1. top-left 2 x 2 square
1. top-right 2 x 2 square
1. last 5 rows from every other column

In [ ]:
array = np.arange(20 * 20).reshape(20, 20)

In [ ]:
array[FILL_ME_IN]

## Exercise: N-dimensional selection

## Exercise: Selections with boolean arrays.

In [ ]:
array = rand.normal(0, 1, 50)

Write an expression to select the positive values from the array.

Write an expression to select the values less than -1 **or** greater than 1.5.

In [ ]:
array = rand.normal(0, 1, 50)

Write an expression that produces the value from `array` if the value is positive, and produces the **square** of the value if it's negative.

In [ ]:
array = np.arange(-5, 5)

In [ ]:
np.where?

## Exercise: "FizzBuzz"

Write an expression that converts `array` into a new array of the same shape according to the following rules:

At each index `[i]`

- if `array[i]` is divisible by 3: `result[i]` should hold -1
- if `array[i]` is divisible by 5: `result[i]` should hold -2
- if `array[i]` is divisible by 15, `result[i]` should hold -3
- otherwise:`result[i]` should hold `array[i]`

(**Hint:** `np.select` works like `np.where`, but it can select from more than two arrays.)

In [ ]:
array = np.arange(1, 100)
np.select?

## Exercise: N-dimensional FizzBuzz

Same rules as above, but on a 3-dimensional array. (HINT: It's possible to write a solution that works for this exercise and the previous one.)

In [ ]:
array = np.arange(1, 100).reshape(3, 11, 3)